apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ac047e2f-e290-4041-9312-2e452303bb11"
    keyvaultName: "aishore-kv-useast"
    objects: |
      array:
        - |
          objectName: sql-database-connect-string
          objectType: secret
        - |
          objectName: blob-storage-connect-key
          objectType: secret
        - |
          objectName: blob-storage-connect-string
          objectType: secret
    tenantId: "3abf0d6f-4f1d-44e5-98c8-b9ce192c038f"
  secretObjects:
    - secretName: azure-kvs
      type: Opaque
      data:
        - objectName: sql-database-connect-string
          key: sql-database-connect-string
        - objectName: blob-storage-connect-key
          key: blob-storage-connect-key
        - objectName: blob-storage-connect-string
          key: blob-storage-connect-string

