apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter-app
  template:
    metadata:
      labels:
        app: flutter-app
    spec:
      containers:
      - name: flutter-app
        image: aishoredev.azurecr.io/flutter-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
